site_name: CodeSutraHub Documentation
theme:
  name: cinder
nav:
  - Home: index.md
  - Tools:
    - HFilePathManager: HFilePathManager/index.md
    - HPanelToolbox: HPanelToolbox/index.md
  - About: about.md
