site_name: Mahendra Pawar Portfolio Documentation
theme:
  name: rtd-dropdown
nav:
  - Getting Started: index.md
  - Tools:
    - Houdini FilePath Manager: HFilePathManager/index.md
    - Houdini Panel ToolBox: HPanelToolBox/index.md
    - Project Hierarchy Generator: ProjectHierarchyGenerator/index.md
  # - About: about.md
