site_name: CodeSutraHub Documentation
theme:
  name: rtd-dropdown
nav:
  - Home: index.md
  - HFilePathManager: HFilePathManager/index.md
  - HPanelToolbox: HPanelToolBox/index.md
  - ProjectHierarchyGenerator: ProjectHierarchyGenerator/index.md
  - About: about.md
